### ISSUE TITLE
duplicate dict key (percona_cluster)

### ISSUE THREAD

**Issue by ygwane** [csuka/ansible_role_percona_xtradb_cluster#1]
Hi,

trying this project but i have an issue on asserts controls when building bootstrappers_list.

Here is my config section for cluster nodes:
```
# replication settings
percona_cluster:
  enabled: true
  name: 'galera-cluster'
  role: master  # master or arbiter
  bootstrapper: false
  server_id: '1'  # must be unique
  ip_address: 192.168.0.176

percona_cluster:
  enabled: true
  name: 'galera-cluster'
  role: master  # master or arbiter
  bootstrapper: false
  server_id: '2'  # must be unique
  ip_address: 192.168.0.177

percona_cluster:
  enabled: true
  name: 'galera-cluster'
  role: master  # master or arbiter
  bootstrapper: true
  server_id: '3'  # must be unique
  ip_address: 192.168.0.178
```

Here is the error output when playing the ansible role:
`TASK [percona_xtradb_cluster : assert | that there is exactly one bootstrapper] *************************************************************************************************************************************************************
fatal: [s2pclust01]: FAILED! => {
    "assertion": "bootstrappers_list | length == 1",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
`
BTW, ansible warning is printed a the beginning of the playbook play:
`[WARNING]: While constructing a mapping from /home/my_ansible/ansible-cluster/roles/percona_xtradb_cluster/defaults/main.yml, line 2, column 1, found a duplicate dict key (percona_cluster). Using last defined value only.
`

Please let me know what i am doing wrong.

Thanks in advance.

**Comment by csuka** [comment]
Hi.

Couple of questions/remarks:

1. are you using latest version?
2. do you only have 1 host in the play? If so, you can remove the replication configuration  as these are not required.

If that doesn’t solve it, please share a complete configuration per host and post complete ansible output on pastebin, and paste here.

**Comment by ygwane** [comment]
Thank you for your answer.

Yes, the git clone was made this morning

I have 3 target hosts, host configuration is pasted on my first message, nothing else was changed into roles/percona_xtradb_cluster/defaults/main.yml file execpt passwords:
```
# custom configuration, see readme
percona_custom_cnf: {}

# replication settings
percona_cluster:
  enabled: true
  name: 'galera-cluster'
  role: master  # master or arbiter
  bootstrapper: true
  server_id: '1'  # must be unique
  ip_address: 192.168.0.176

percona_cluster:
  enabled: true
  name: 'galera-cluster'
  role: master  # master or arbiter
  bootstrapper: false
  server_id: '2'  # must be unique
  ip_address: 192.168.0.177

percona_cluster:
  enabled: true
  name: 'galera-cluster'
  role: master  # master or arbiter
  bootstrapper: false
  server_id: '3'  # must be unique
  ip_address: 192.168.0.178

percona_expire_logs_seconds: 86400
percona_max_binlog_size: 100M
percona_binlog_format: ROW
percona_replication_user: sst
```
Ansible output is here: https://pastebin.com/2qV4quth

Thank you
