### ISSUE TITLE
Cluster

### ISSUE THREAD

**Issue by Lestanen** [csuka/ansible_role_percona_xtradb_cluster#5]
Hello, i have a little problem. i run the role and everything seems to be right, not errors but i cant make the cluster works, on mysql the cluster size still 1 and there is not replication beetwen the nodes. 

I have 1 Boostrapper
2 nodes
1 arbiter

**Comment by csuka** [comment]
That's a very specific problem. I need way more details.
Either provide more details, or we need to connect and I need to see what happens.

**Comment by Lestanen** [comment]
Hi, sure. Can you tell me when you can be available to connect? Enviado desde mi iPhoneEl 1 sept 2023, a las 11:59, Me ***@***.***> escribió:﻿
That's a very specific problem. I need way more details.
Either provide more details, or we need to connect and I need to see what happens.

**Comment by csuka** [comment]
It would be hard to connect since I'm quite busy. Just to verify:
Once you have your vm's up and running and clustering did not happen.

Can you execute from host to host:
telnet (ip) 3306?

ofc, the IP you gave w:

```yaml
# vars for node2
percona_cluster:
  name: 'test-cluster'
  enabled: true
  role: master
  bootstrapper: false
  server_id: '2'
  ip_address: 10.0.0.112
```
